### ISSUE TITLE
Preview should not be default, Preview does not work, Documentation is wrong

### ISSUE THREAD

**Issue by beath** [mhirdes/go_maps_ext#40]
As of 2.4.0 the maps are not loaded per default but only a preview (or at least that's how it should be as far as I can tell).

1. The "show maps" link which is displayed instead of the map does not work. The map cannot be displayed. Since this is the new default behaviour the update to 2.4.0 is a breaking change.

2. The new preview feature should not be default. Best practise to introduce new features is to make them optional at least in the beginning. plugin.tx_gomapsext.settings.preview.enabled should be 0 by default. Especially given that it doesn't work always/yet.

3. The documentation is wrong: https://docs.typo3.org/typo3cms/extensions/go_maps_ext/Configuration/Reference/Index.html#extension-configurations . The Variable has the same description as settings.infoWindow.imageMaxWidth.

![show-map-not-working](https://user-images.githubusercontent.com/13386157/42088271-59726cbe-7b99-11e8-9dbd-16e8b8beb44d.png)
![docu-wrong](https://user-images.githubusercontent.com/13386157/42088272-598f2b06-7b99-11e8-8b4f-6cd5c2a4ba06.png)

**Comment by beath** [comment]
Hi Marc,

Well, removing the default fixes the extension. Correct documentation is always nice.

In our installation the feature itself did not work. It was not possible to display the map and there was no preview. The „show map“ link had no effect.

I guess that this feature worked in your installation because otherwise you wouldn’t have published it. I cannot tell why it doesn’t work. My guesses would be JS inclusion, CSS classes or HTML structure which might differ at some point. So to fix the feature you would first have to reproduce the issue which could be difficult. You could start by installing your extension on vanilla TYPO3 and testing it.

Cheers
Beat

**Comment by mhirdes** [comment]
Hi Beat,

 

so everything is prepared for a new release. The documentation was already updated and now I reseted the default value for the preview. This also will be a "breaking change" but ok. 

 

For sure we tested this in diverent enviroments. I would like to have a look on your system. Otherwise I can't reproduce the error. It's ok if you don't like to. Than I would publish a release immediately. 

 

Kind regards,

Marc



Gesendet: Freitag, 29. Juni 2018 um 15:29 Uhr
Von: beath <notifications@github.com>
An: mhirdes/go_maps_ext <go_maps_ext@noreply.github.com>
Cc: mhirdes <Marc_Hirdes@gmx.de>, Comment <comment@noreply.github.com>
Betreff: Re: [mhirdes/go_maps_ext] Preview should not be default, Preview does not work, Documentation is wrong (#40)

Hi Marc,

Well, removing the default fixes the extension. Correct documentation is always nice.

In our installation the feature itself did not work. It was not possible to display the map and there was no preview. The „show map“ link had no effect.

I guess that this feature worked in your installation because otherwise you wouldn’t have published it. I cannot tell why it doesn’t work. My guesses would be JS inclusion, CSS classes or HTML structure which might differ at some point. So to fix the feature you would first have to reproduce the issue which could be difficult. You could start by installing your extension on vanilla TYPO3 and testing it.

Cheers
Beat
