### ISSUE TITLE
Map is not draggable

### ISSUE THREAD

**Issue by Rinxiao** [mhirdes/go_maps_ext#95]
Extension Version: 4.2.0
TYPO3 Version: 10.4.30

Even though it is checked in the map data record, the map on the frontend is no longer draggable after updating to version 4.2.0.

**Comment by mhirdes** [comment]
Please take a look at your map record. If the scroll zoom is disabled, also the dragging is disabled. Since 2017 there is only a setting available for gesture handling in Google Maps. https://developers.google.com/maps/documentation/javascript/interaction

In furthure version I will find a better way to descripe this behaviour in the backend.

**Comment by Rinxiao** [comment]
Thanks for the fast reply! You're right. The map is draggable in this version when I enable scroll zoom in the backend. The scroll zoom in the frontend is disabled, though. I don't think the scroll zoom improves the user experience, thus it's ok for me. But it's really confusing. As you mentioned, a better description in the future would sort that out.

What I don't understand is how both behaviors worked as they are described in version 4.1.0. Have you since switched to a different API?
