### ISSUE TITLE
Not GDPR compliant

### ISSUE THREAD

**Issue by ProWebs** [mhirdes/go_maps_ext#97]
The plugin allows google maps to reload google fonts from google server.

This means that the plugin is no longer legally compliant and the websites that use the plugin can be warned.

**Comment by mhirdes** [comment]
Thanks for your comment. First time that I hear that. Is it a problem when Google uses a Google Service? The User have to agree to load the map from Google, right?

The solution would be to explain that the map and the font is loaded from Google or what else?

**Comment by tamm78** [comment]
Hello, our company has now received a warning from a law firm in this regard. We have taken a closer look at the problem. It is true that you can configure the map so that it is only loaded after the tracking has been approved (optin). However, the problem is that regardless of this decision, the extension embeds Google Fonts in the head of the page (Roboto + Google Sans). The privacy violation already takes place before the consent and thus the extension is not GDPR compliant. Can you integrate the Google Fonts so that they are only loaded with the map and not before? Thank you!

**Comment by ProWebs** [comment]
Its not a problem if google use googles services if your are on google, but if you are on another website and this site provides google your personal ip without your agreement its a big problem.

It would be great if there is a configuration for disable loading google fonts from google server or to replace them with local fonts.

**Comment by mhirdes** [comment]
We don't load any Google Fonts. You can search in this repository for Roboto or Google Sans and you'll not find anything. Please check your website. If you want we can take a look together. Therefore write me on slack. But I guess you mention an issue here that doese not belong to this extension.

**Comment by ProWebs** [comment]
You especally not but google maps does.

**Comment by ProWebs** [comment]
Take a look here:
![Unbenannt](https://user-images.githubusercontent.com/16188629/194563706-ed1caf81-447b-44d8-b975-6e2d288c7bc4.PNG)

https://www.digitale-fotografien.com/anfahrt

I don't know if there a api solution to solve it from your extension.

**Comment by ProWebs** [comment]
Take a look here:
https://demo.t3planet.com/t3-extensions/google-map

They solved the issues in a good way.

**Comment by mhirdes** [comment]
@ProWebs if you have still troubles with go_maps_ext please contact me. All in all you can easily configure the extension to load the map only after the user confirms. Also we don't load any Google Fonts.

**Comment by ProWebs** [comment]
Is there a manuel for "loading the maps only after user confirmation"? You don't load google fonts but google maps do it.

**Comment by ProWebs** [comment]
You also had a solution for made for one of your customers using the same extension. But i don't see any option to activate it.
https://www.zp-schulung.de/anfahrt/

Maybe you will update the extension with this feature in future or add a tutorial for setup it.

**Comment by mhirdes** [comment]
1.) see https://github.com/mhirdes/go_maps_ext/issues/78

It is not possible to provide a one click solution out of the box, that works with every consent management tool.

We use our own developed consent tool, because in our opinion, to use an external is also not very GDPR compliant. Because when the tool is loaded the user also provides his IP address. 

This consent tool is not developed to be published right now.

 2.) Again, to load a font is ok, when also the map is loaded from Google. Important is, that the user confirms it. Google Font and Google Maps belongs both to Google.

3.) Again, May you can contact me on slack, call me +49 341 / 35 00 25 33 or write me a mail.
